// <auto-generated />
using System;
using Lesson11_EntityFrameworkCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lesson11_EntityFrameworkCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Lesson11_EntityFrameworkCore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Soft drinks, coffees, teas, beers, and ales",
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sweet and savory sauces, relishes, spreads, and seasonings",
                            Name = "Condiments"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Desserts, candies, and sweet breads",
                            Name = "Confections"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cheeses",
                            Name = "Dairy Products"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Breads, crackers, pasta, and cereal",
                            Name = "Grains/Cereals"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Prepared meats",
                            Name = "Meat/Poultry"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Dried fruit and bean curd",
                            Name = "Produce"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Seaweed and fish",
                            Name = "Seafood"
                        });
                });

            modelBuilder.Entity("Lesson11_EntityFrameworkCore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("money");

                    b.Property<short?>("UnitsInStock")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Chai",
                            SupplierId = 1,
                            UnitPrice = 18.00m,
                            UnitsInStock = (short)39
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Chang",
                            SupplierId = 1,
                            UnitPrice = 19.00m,
                            UnitsInStock = (short)17
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Aniseed Syrup",
                            SupplierId = 1,
                            UnitPrice = 10.00m,
                            UnitsInStock = (short)13
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Chef Anton's Cajun Seasoning",
                            SupplierId = 2,
                            UnitPrice = 22.00m,
                            UnitsInStock = (short)53
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Chef Anton's Gumbo Mix",
                            SupplierId = 2,
                            UnitPrice = 21.35m,
                            UnitsInStock = (short)0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Grandma's Boysenberry Spread",
                            SupplierId = 3,
                            UnitPrice = 25.00m,
                            UnitsInStock = (short)120
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Name = "Uncle Bob's Organic Dried Pears",
                            SupplierId = 3,
                            UnitPrice = 30.00m,
                            UnitsInStock = (short)15
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Northwoods Cranberry Sauce",
                            SupplierId = 3,
                            UnitPrice = 40.00m,
                            UnitsInStock = (short)6
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            Name = "Mishi Kobe Niku",
                            SupplierId = 4,
                            UnitPrice = 97.00m,
                            UnitsInStock = (short)29
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 8,
                            Name = "Ikura",
                            SupplierId = 4,
                            UnitPrice = 31.00m,
                            UnitsInStock = (short)31
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Name = "Queso Cabrales",
                            SupplierId = 5,
                            UnitPrice = 21.00m,
                            UnitsInStock = (short)22
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "Queso Manchego La Pastora",
                            SupplierId = 5,
                            UnitPrice = 38.00m,
                            UnitsInStock = (short)86
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 8,
                            Name = "Konbu",
                            SupplierId = 6,
                            UnitPrice = 6.00m,
                            UnitsInStock = (short)24
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            Name = "Tofu",
                            SupplierId = 6,
                            UnitPrice = 23.25m,
                            UnitsInStock = (short)35
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Name = "Genen Shouyu",
                            SupplierId = 6,
                            UnitPrice = 15.50m,
                            UnitsInStock = (short)39
                        });
                });

            modelBuilder.Entity("Lesson11_EntityFrameworkCore.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "49 Gilbert St.",
                            CompanyName = "Exotic Liquids",
                            Phone = "(171) 555-2222"
                        },
                        new
                        {
                            Id = 2,
                            Address = "P.O. Box 78934",
                            CompanyName = "New Orleans Cajun Delights",
                            Phone = "(100) 555-4822"
                        },
                        new
                        {
                            Id = 3,
                            Address = "707 Oxford Rd.",
                            CompanyName = "Grandma Kelly's Homestead",
                            Phone = "(313) 555-5735"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Sekimai Musashino-shi",
                            CompanyName = "Tokyo Traders",
                            Phone = "(03) 3555-5011"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Calle del Rosal 4",
                            CompanyName = "Cooperativa de Quesos",
                            Phone = "(98) 598 76 54"
                        },
                        new
                        {
                            Id = 6,
                            Address = "92 Setsuko Chuo-ku",
                            CompanyName = "Mayumi's",
                            Phone = "(06) 431-7877"
                        });
                });

            modelBuilder.Entity("Lesson11_EntityFrameworkCore.Models.Product", b =>
                {
                    b.HasOne("Lesson11_EntityFrameworkCore.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Lesson11_EntityFrameworkCore.Models.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId");
                });
#pragma warning restore 612, 618
        }
    }
}
